"""initial migration

Revision ID: b2dfb140f496
Revises: 
Create Date: 2026-08-06 14:17:19.492555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dfb140f496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=500), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
