"""initial migrate

Revision ID: b2ea15c5a7a0
Revises: 
Create Date: 2026-08-07 10:24:42.322171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ea15c5a7a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('grievance',
    sa.Column('g_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('audio', mysql.LONGBLOB(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['committee.c_id'], ),
    sa.PrimaryKeyConstraint('g_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grievance')
    op.drop_table('committee')
    # ### end Alembic commands ###
